"use client";
import { useRef,useState } from "react";
type Job={name:string;quantity:number;remaining:string;preview:string;character:number};
const references=[
 ["a0","Capital Ship Maintenance"],["a1","Capital Capacitor Battery"],["a2","Capital Power Generator"],["a3","Capital Launcher"],
 ["a4","Capital Armor Plates"],["a5","Capital Sensor Cluster"],["a6","Capital Shield Emitter"],["a7","Capital Siege Array"],
 ["b0","Capital Cargo Bay"],["b1","Capital Computer"],["b2","Capital Construction"],["b3","Capital Clone Vat Bay"],
 ["b4","Capital Corporate Hanga"],["b5","Capital Doomsday"],["b6","Capital Turret Hardpoint"],["b7","Capital Jump Bridge"],
 ["b8","Capital Jump Drive"],["b9","Capital Propulsion"],["b10","Capital Drone Bay"]
] as const;
function hash(source:CanvasImageSource,tile=false){const c=document.createElement("canvas");c.width=8;c.height=8;const x=c.getContext("2d")!;if(tile){const s=source as HTMLCanvasElement;x.drawImage(s,s.width*.1,s.height*.12,s.width*.8,s.height*.58,0,0,8,8)}else x.drawImage(source,0,0,8,8);const d=x.getImageData(0,0,8,8).data,v:number[]=[];for(let i=0;i<d.length;i+=4)v.push(d[i]*.299+d[i+1]*.587+d[i+2]*.114);const m=v.reduce((a,b)=>a+b,0)/v.length;return v.map(n=>n>m?"1":"0").join("")}
function gap(a:string,b:string){let n=0;for(let i=0;i<64;i++)if(a[i]!==b[i])n++;return n}
async function library(names:string[]){return Promise.all(references.map(async([file,prefix])=>{const image=new Image();image.src="/cap-icons/"+file+".png";await image.decode();return{hash:hash(image),name:names.find(n=>n.toLowerCase().startsWith(prefix.toLowerCase()))||prefix}}))}
export default function OvenImporter({onImport}:{onImport:(jobs:Array<Omit<Job,"preview">>)=>void}){
 const ref=useRef<HTMLInputElement>(null),[busy,setBusy]=useState(false),[jobs,setJobs]=useState<Job[]>([]),[names,setNames]=useState<string[]>([]),[status,setStatus]=useState("");
 async function scan(files:FileList){setBusy(true);setJobs([]);setStatus("Reading active oven slots and matching capital-part icons…");let itemNames:string[]=[];try{const raw=await(await fetch("/api/items")).json();const list=Array.isArray(raw)?raw:raw["hydra:member"]||raw.items||raw.data||[];itemNames=list.map((x:Record<string,unknown>)=>String(x.name||x.itemName||"")).filter(Boolean).sort();setNames(itemNames)}catch{}const refs=await library(itemNames);
  const {createWorker}=await import("tesseract.js");const worker=await createWorker("eng"),found:Job[]=[];await worker.setParameters({tessedit_char_whitelist:"0123456789:day"});
  for(let f=0;f<Math.min(4,files.length);f++){const image=new Image();image.src=URL.createObjectURL(files[f]);await image.decode();const cellH=image.height/2,cellW=cellH*.81;
   for(let slot=0;slot<10;slot++){const row=Math.floor(slot/5),col=slot%5,x=col*cellW,y=row*cellH,c=document.createElement("canvas");c.width=Math.round(cellW);c.height=Math.round(cellH);c.getContext("2d")!.drawImage(image,x,y,cellW,cellH,0,0,c.width,c.height);const result=await worker.recognize(c),text=result.data.text.replace(/\s+/g," ").trim(),nums=text.match(/\d+/g)||[];const quantity=Math.min(10,Number(nums[0]||0));if(!quantity)continue;const remaining=(text.match(/\d+\s*day|\d{1,3}:\d{2}:\d{2}/i)||[])[0]||"Check time",h=hash(c,true),match=refs.sort((a,b)=>gap(h,a.hash)-gap(h,b.hash))[0];found.push({name:match&&gap(h,match.hash)<=22?match.name:"",quantity,remaining,preview:c.toDataURL("image/png"),character:f+1})}URL.revokeObjectURL(image.src)}
  await worker.terminate();setJobs(found);const matched=found.filter(j=>j.name).length;setStatus(found.length+" active jobs found; "+matched+" capital-part icons identified automatically. Confirm before saving.");setBusy(false)}
 return <div className="importer"><div className="importTop"><div><b>Import oven screenshots</b><small>Select up to four screenshots together—one per character.</small></div><button disabled={busy} onClick={()=>ref.current?.click()}>{busy?"Scanning…":"Choose oven screenshots"}</button><input hidden multiple ref={ref} type="file" accept="image/*" onChange={e=>e.target.files?.length&&scan(e.target.files)}/></div>{status&&<p className="statusline">{status}</p>}{jobs.length>0&&<><datalist id="oven-items">{names.map(n=><option key={n} value={n}/>)}</datalist><div className="detections">{jobs.map((j,i)=><div className="detected" key={i}><img src={j.preview} alt="Oven job"/><div><input list="oven-items" placeholder="Confirm item name" value={j.name} onChange={e=>setJobs(a=>a.map((x,k)=>k===i?{...x,name:e.target.value}:x))}/><small>Character {j.character} · {j.remaining} remaining</small></div><input type="number" min="1" max="10" value={j.quantity} onChange={e=>setJobs(a=>a.map((x,k)=>k===i?{...x,quantity:Math.min(10,Number(e.target.value))}:x))}/></div>)}</div><button disabled={jobs.some(j=>!j.name)} onClick={()=>onImport(jobs.map(({preview,...j})=>j))}>Save current oven snapshot</button></>}</div>
}
