"use client";
import { useRef,useState } from "react";
type Detection={id:string;name:string;quantity:number;preview:string;hash:string;source:number;confidence:number};
type ItemRef={name:string;icon:string;hash?:string};
type Props={onImport:(items:Array<{name:string;quantity:number}>,mode:"add"|"replace")=>void};
function crop(source:HTMLImageElement,x:number,y:number,w:number,h:number){const c=document.createElement("canvas");c.width=Math.max(1,Math.round(w));c.height=Math.max(1,Math.round(h));c.getContext("2d")!.drawImage(source,x,y,w,h,0,0,c.width,c.height);return c}
function hash(source:CanvasImageSource){const c=document.createElement("canvas");c.width=8;c.height=8;const x=c.getContext("2d")!;x.drawImage(source,0,0,8,8);const d=x.getImageData(0,0,8,8).data,v:number[]=[];for(let i=0;i<d.length;i+=4)v.push(d[i]*.299+d[i+1]*.587+d[i+2]*.114);const m=v.reduce((a,b)=>a+b,0)/v.length;return v.map(n=>n>m?"1":"0").join("")}
function gap(a:string,b:string){let n=0;for(let i=0;i<64;i++)if(a[i]!==b[i])n++;return n}
function parseQuantity(text:string){const clean=text.toUpperCase().replace(/,/g,"").replace(/\s/g,"");const match=clean.match(/(\d+(?:\.\d+)?)K?/);if(!match)return 0;const n=Number(match[1]);return Math.round(n*(clean.includes("K")?1000:1))}
function gridStep(image:HTMLImageElement,axis:"x"|"y"){const c=document.createElement("canvas");const scale=Math.min(1,900/Math.max(image.width,image.height));c.width=Math.round(image.width*scale);c.height=Math.round(image.height*scale);const x=c.getContext("2d")!;x.drawImage(image,0,0,c.width,c.height);const d=x.getImageData(0,0,c.width,c.height).data,size=axis==="x"?c.width:c.height,other=axis==="x"?c.height:c.width,scores=new Array(size).fill(0);for(let p=1;p<size;p++){let sum=0,count=0;for(let q=0;q<other;q+=3){const i=axis==="x"?(q*c.width+p)*4:(p*c.width+q)*4,j=axis==="x"?(q*c.width+p-1)*4:((p-1)*c.width+q)*4;sum+=Math.abs(d[i]-d[j])+Math.abs(d[i+1]-d[j+1])+Math.abs(d[i+2]-d[j+2]);count++}scores[p]=sum/count}let best=80,bestScore=-1;for(let lag=55;lag<=Math.min(220,size/2);lag++){let s=0,n=0;for(let i=1;i+lag<size;i++){s+=scores[i]*scores[i+lag];n++}s/=Math.max(1,n);if(s>bestScore){bestScore=s;best=lag}}let offset=0,offsetScore=-1;for(let o=0;o<best;o++){let s=0;for(let p=o;p<size;p+=best)s+=scores[p];if(s>offsetScore){offsetScore=s;offset=o}}return{step:best/scale,offset:offset/scale}}
async function referenceLibrary(){const raw=await(await fetch("/api/items")).json(),items=Array.isArray(raw)?raw:raw["hydra:member"]||raw.items||raw.data||[];const useful=items.filter((i:Record<string,unknown>)=>/ore|mineral|planet|material|component|fullerite|alloy|compound|metal|fiber|gas|crystal|coolant|condensate|nanite|plastic|polyaramid|glass|construction|capital/i.test(String(i.category_name||"")+" "+String(i.group_name||"")+" "+String(i.name||""))).slice(0,500);return useful.map((i:Record<string,unknown>)=>({name:String(i.name),icon:"/api/icon/"+String(i.icon_id)})) as ItemRef[]}
async function loadHashes(refs:ItemRef[]){const queue=[...refs];await Promise.all(new Array(8).fill(0).map(async()=>{while(queue.length){const r=queue.shift()!;try{const image=new Image();image.src=r.icon;await image.decode();r.hash=hash(image)}catch{}}}));return refs.filter(r=>r.hash)}
export default function InventoryImporter({onImport}:Props){
 const fileRef=useRef<HTMLInputElement>(null),[busy,setBusy]=useState(false),[status,setStatus]=useState(""),[rows,setRows]=useState<Detection[]>([]),[names,setNames]=useState<string[]>([]);
 async function scan(files:FileList){setBusy(true);setRows([]);setStatus("Loading Echoes item references…");const refs=await referenceLibrary();setNames(refs.map(r=>r.name).sort());await loadHashes(refs);const {createWorker}=await import("tesseract.js"),worker=await createWorker("eng");await worker.setParameters({tessedit_char_whitelist:"0123456789.,Kk"});const found:Detection[]=[];
  for(let f=0;f<files.length;f++){const image=new Image();image.src=URL.createObjectURL(files[f]);await image.decode();const gx=gridStep(image,"x"),gy=gridStep(image,"y");let checked=0;for(let y=gy.offset;y+gy.step<=image.height;y+=gy.step)for(let x=gx.offset;x+gx.step<=image.width;x+=gx.step){checked++;setStatus("Screenshot "+(f+1)+"/"+files.length+": checking tile "+checked+"…");const tile=crop(image,x+2,y+2,gx.step-4,gy.step-4),quantityCrop=crop(image,x,y+gy.step*.68,gx.step,gy.step*.32),result=await worker.recognize(quantityCrop),quantity=parseQuantity(result.data.text);if(!quantity)continue;const icon=crop(image,x+gx.step*.12,y+gy.step*.12,gx.step*.76,gy.step*.55),h=hash(icon),ranked=refs.filter(r=>r.hash).map(r=>({r,d:gap(h,r.hash!)})).sort((a,b)=>a.d-b.d),best=ranked[0],confidence=best?Math.max(0,100-Math.round(best.d/64*160)):0;const duplicate=found.find(v=>v.quantity===quantity&&gap(v.hash,h)<=5);if(!duplicate)found.push({id:f+"-"+x+"-"+y,name:best&&best.d<=22?best.r.name:"",quantity,preview:tile.toDataURL("image/png"),hash:h,source:f+1,confidence})}URL.revokeObjectURL(image.src)}
  await worker.terminate();setRows(found);setStatus(found.length+" unique stacks found across "+files.length+" screenshot(s). Overlap duplicates were removed; review low-confidence matches.");setBusy(false)}
 return <div className="importer"><div className="importTop"><div><b>Import inventory screenshots</b><small>Any resolution, crop, row count, or number of visible slots. Select overlapping screenshots together.</small></div><button onClick={()=>fileRef.current?.click()} disabled={busy}>{busy?"Scanning…":"Choose screenshots"}</button><input hidden multiple ref={fileRef} type="file" accept="image/*" onChange={e=>e.target.files?.length&&scan(e.target.files)}/></div>{status&&<p className="statusline">{status}</p>}{rows.length>0&&<><datalist id="echoes-items">{names.map(n=><option key={n} value={n}/>)}</datalist><div className="detections">{rows.map((r,i)=><div className="detected" key={r.id}><img src={r.preview} alt="Detected inventory tile"/><div><input list="echoes-items" value={r.name} placeholder="Confirm uncertain item" onChange={e=>setRows(a=>a.map((x,j)=>j===i?{...x,name:e.target.value}:x))}/><small>Screenshot {r.source} · {r.confidence}% match</small></div><input type="number" value={r.quantity} onChange={e=>setRows(a=>a.map((x,j)=>j===i?{...x,quantity:Number(e.target.value)}:x))}/></div>)}</div><div className="importActions"><button disabled={rows.some(r=>!r.name||!r.quantity)} onClick={()=>onImport(rows,"replace")}>Use as current inventory snapshot</button><button className="ghost" disabled={rows.some(r=>!r.name||!r.quantity)} onClick={()=>onImport(rows,"add")}>Add as delivery</button></div></>}</div>
}
