"use client";
import { useRef, useState } from "react";

type Detection={id:string;name:string;quantity:number;preview:string;hash:string;source:number};
type Props={onImport:(items:Array<{name:string;quantity:number}>,mode:"add"|"replace")=>void};

function makeCrop(source:HTMLImageElement,x:number,y:number,w:number,h:number){const c=document.createElement("canvas");c.width=Math.max(1,w);c.height=Math.max(1,h);c.getContext("2d")!.drawImage(source,x,y,w,h,0,0,w,h);return c}
function fingerprint(canvas:HTMLCanvasElement){const c=document.createElement("canvas");c.width=8;c.height=8;const ctx=c.getContext("2d")!;ctx.drawImage(canvas,0,0,8,8);const d=ctx.getImageData(0,0,8,8).data;const values=[];for(let i=0;i<d.length;i+=4)values.push(Math.round((d[i]*.299+d[i+1]*.587+d[i+2]*.114)/16));const mean=values.reduce((a,b)=>a+b,0)/values.length;return values.map(v=>v>mean?"1":"0").join("")}
function distance(a:string,b:string){let n=0;for(let i=0;i<Math.min(a.length,b.length);i++)if(a[i]!==b[i])n++;return n+Math.abs(a.length-b.length)}

export default function InventoryImporter({onImport}:Props){
 const fileRef=useRef<HTMLInputElement>(null);const [busy,setBusy]=useState(false);const [status,setStatus]=useState("");const [rows,setRows]=useState<Detection[]>([]);const [names,setNames]=useState<string[]>([]);
 async function loadNames(){if(names.length)return names;try{const raw=await(await fetch("/api/items")).json();const list=Array.isArray(raw)?raw:raw["hydra:member"]||raw.member||raw.items||raw.data||[];const parsed=list.map((x:Record<string,unknown>)=>String(x.name||x.itemName||x.title||"")).filter(Boolean).sort();setNames(parsed);return parsed}catch{return[]}}
 async function scan(files:FileList){
  setBusy(true);setRows([]);setStatus("Preparing screenshots…");await loadNames();const {createWorker}=await import("tesseract.js");const worker=await createWorker("eng");await worker.setParameters({tessedit_char_whitelist:"0123456789"});const found:Detection[]=[];let scanned=0;
  for(let f=0;f<files.length;f++){const image=new Image();image.src=URL.createObjectURL(files[f]);await image.decode();const sx=image.width/1157,sy=image.height/683;const left=Math.round(119*sx),top=Math.round(220*sy),stepX=Math.round(104*sx),stepY=Math.round(121*sy),cellW=Math.round(96*sx),iconH=Math.round(78*sy),qtyOffset=Math.round(74*sy),qtyH=Math.round(31*sy);const right=Math.round(image.width*.985),bottom=Math.round(image.height*.86);const columns=Math.max(1,Math.floor((right-left-cellW)/stepX)+1),rowCount=Math.max(1,Math.floor((bottom-top-iconH)/stepY)+1);
   for(let row=0;row<rowCount;row++)for(let col=0;col<columns;col++){const x=left+col*stepX,y=top+row*stepY;if(x+cellW>image.width||y+qtyOffset+qtyH>image.height)continue;scanned++;setStatus(`Screenshot ${f+1}/${files.length}: checking visible slot ${scanned}…`);const icon=makeCrop(image,x,y,cellW,iconH),preview=icon.toDataURL("image/png"),hash=fingerprint(icon);const result=await worker.recognize(makeCrop(image,x,y+qtyOffset,cellW,qtyH).toDataURL("image/png"));const quantity=Number(result.data.text.replace(/\D/g,""));if(!quantity)continue;const duplicate=found.find(existing=>existing.quantity===quantity&&distance(existing.hash,hash)<=5);if(!duplicate)found.push({id:`${f}-${row}-${col}`,name:"",quantity,preview,hash,source:f+1})}
   URL.revokeObjectURL(image.src);
  }
  await worker.terminate();setRows(found);setStatus(`${found.length} unique item stacks found across ${files.length} screenshot${files.length===1?"":"s"}. Overlapping duplicates were removed.`);setBusy(false)
 }
 return <div className="importer"><div className="importTop"><div><b>Import inventory screenshots</b><small>Select one or several overlapping screenshots from the same inventory snapshot.</small></div><button onClick={()=>fileRef.current?.click()} disabled={busy}>{busy?"Scanning…":"Choose screenshots"}</button><input hidden multiple ref={fileRef} type="file" accept="image/*" onChange={e=>e.target.files?.length&&scan(e.target.files)}/></div>{status&&<p className="statusline">{status}</p>}{rows.length>0&&<><datalist id="echoes-items">{names.map(n=><option key={n} value={n}/>)}</datalist><div className="detections">{rows.map((r,i)=><div className="detected" key={r.id}><img src={r.preview} alt="Detected item icon"/><div><input list="echoes-items" value={r.name} placeholder="Search item name" onChange={e=>setRows(a=>a.map((x,j)=>j===i?{...x,name:e.target.value}:x))}/><small>Screenshot {r.source}</small></div><input type="number" value={r.quantity} onChange={e=>setRows(a=>a.map((x,j)=>j===i?{...x,quantity:Number(e.target.value)}:x))}/></div>)}</div><div className="importActions"><button disabled={rows.some(r=>!r.name||!r.quantity)} onClick={()=>onImport(rows,"add")}>Add to inventory</button><button className="ghost" disabled={rows.some(r=>!r.name||!r.quantity)} onClick={()=>onImport(rows,"replace")}>Replace quantities</button></div></>}</div>
}
